fix: error on ttsPlayer close if init had not completed
Instead, we wait for the job to complete, then call .close()
 or the job fails, which is also OK, as it will have cleaned itself up

Before the fix the error was:

```
 ttsPlayer close()
 java.lang.IllegalStateException: This job has not completed yet
```

from `DeferredCoroutine.getCompleted`

Fixes 19595